version: '2'

services: 

    api:
        build:
            context: api
            dockerfile: Dockerfile
        container_name: api
        restart: always
        depends_on: 
            - test-mongo
        networks: 
            - app_network
        ports:
            - "80:3000"
        environment:
            - PORT=3000
            - dbConnString=mongodb://test-mongo:27017/test

    test-mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks: 
            - app_network
        container_name: test-mongo

networks: 
    app_network:
        driver: bridge
